language: node_js
node_js:
- 10.19.0
dist: trusty
sudo: required
addons:
  chrome: stable
#before_install:
#- yarn global add protractor@3.3.0
cache:
  directories:
    - node_modules
install:
#- yarn global add npm@6.0.1
- yarn global add grunt-cli
#- yarn add selenium-webdriver
- yarn
#- ./node_modules/protractor/bin/webdriver-manager update --standalone
#before_script:
#- export CHROME_BIN=chromium-browser
#- export DISPLAY=:99.0
#- sh -e /etc/init.d/xvfb start
script:
- yarn build
- yarn test
# - grunt e2e-test
notifications:
  slack:
    secure: iGLGsYyVIyKVpVVCskGh/zc6Pkqe0D7jpUtbywSbnq6l5seE6bvBVqm0F2FSCIN+AIC+qal2mPEWysDVsLACm5tTEeA8NfL8dmCrAKbiFbi+gHl4mnHHCHl7ii/7UkoIIXNc5UXbgMSXRS5l8UcsSDlN8VxC5zWstbJvjeYIvbA=
